# Generated by Django 5.1.2 on 2024-11-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carmodle_commentmodle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModle',
            new_name='CarModel',
        ),
        migrations.RenameModel(
            old_name='CommentModle',
            new_name='CommentModel',
        ),
    ]
