# Generated by Django 5.1.2 on 2024-11-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_rename_carmodle_carmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='descriptoin',
            field=models.CharField(max_length=500),
        ),
    ]
